server:
  port: 8080

# 配置数据源
spring:
  datasource:
    type: com.zaxxer.hikari.util.DriverDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/working1227?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#    视图解析器
#  thymeleaf:
#    prefix: classpath:/views/


# mybatis相关配置
mybatis:
  # 配置别名需要扫描的包
  type-aliases-package: com.wsl.working1227
  # mapper映射文件
  mapper-locations: classpath:mapper/*.xml
  configuration:
    # 配置日志在控制台显示sql语句
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 开启二级缓存
    cache-enabled: true